# Generated by Django 3.2.7 on 2021-10-29 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0003_auto_20211029_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.AddField(
            model_name='media',
            name='files',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homedia.files'),
            preserve_default=False,
        ),
    ]
