# Generated by Django 3.2.7 on 2021-10-29 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homedia', '0004_auto_20211029_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='files',
        ),
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(default='', editable=False, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='files',
        ),
    ]
