# Generated by Django 3.2.7 on 2021-10-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0006_alter_media_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='upload_at',
        ),
    ]
