# Generated by Django 3.2.7 on 2021-10-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0007_remove_media_upload_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
