# Generated by Django 3.2.7 on 2021-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
