# Generated by Django 3.2.7 on 2021-10-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0011_alter_media_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='thumbnails'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
