# Generated by Django 3.2.7 on 2021-11-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0013_alter_media_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
